# Generated by Django 4.1.12 on 2024-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id_perro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_chip', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('perdido', models.BooleanField()),
                ('fecha_perdido', models.DateField(blank=True, null=True)),
                ('robado', models.BooleanField()),
                ('fecha_robado', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
